### ISSUE TITLE
Add black check for PRs?

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/gufe#112]
Should we add a black check for PRs? We have one in [fah-alchemy](https://github.com/openforcefield/fah-alchemy/blob/main/.github/workflows/black.yaml), for example.

**Comment by dwhswenson** [comment]
No. We are not Black style. We used to have pep8speaks, but apparently it stopped speaking? 🤷‍♂️

**Comment by IAlibay** [comment]
I'd vote for flake8 as a linter action, avoids the unreadable mess that `black` sometimes leads to (we're having issues with darken in MDA)
