### ISSUE TITLE
Move `openfe` `LigandAtomMapping` into `gufe`?

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/gufe#115]
@ijpulidos and I are working on [nonequilibrium cycling](https://github.com/choderalab/perses/pull/1066) in `perses`, and were wondering if [`LigandAtomMapping`](https://github.com/OpenFreeEnergy/openfe/blob/82a6a6db4c22cc5b30ddf26253db10130a24662f/openfe/setup/atom_mapping/ligandatommapping.py#L13) from OpenFreeEnergy/openfe made more sense here in `gufe`? 

The `AtomMapping` base class is an abstract base class, so we can't directly use that, and think it best if we avoid implementing our own child class in `perses` for the mappings used there.

**Comment by IAlibay** [comment]
I wonder if it may make more sense for the protocol to depend on openfe? My understanding is that the long term hope is that openfe acts as a gateway to packaged protocols, so it would make sense for shared classes that implements gufe abstract classes that multiple protocols can use to sit in openfe?

**Comment by dwhswenson** [comment]
`gufe` is the place for data models (the "nouns" in FE). Ligand atom mappings (or more accurately, small molecule atom mappings) are an example of that. I think it is reasonable to move that into here. We have `SmallMolecularComponent`, why not a `SmallMoleculeAtomMapping`?

OTOH, the `AtomMapper` base class (which is expected by the `openfe` network planners) is an OpenFE-specific API for generating mappings. I'm less convinced that it would belong in `gufe`.

**Comment by richardjgowers** [comment]
I think the only problem I can see is that `LigandAtomMapping` has a lot of visualisation code.  So if we're ok with also including that in gufe then sure.

One problem I can see with the status quo is that if we want to package the non-eq Protocol in the openfe app, there'll be a gross circular dependency

**Comment by dwhswenson** [comment]
> I think the only problem I can see is that LigandAtomMapping has a lot of visualisation code. So if we're ok with also including that in gufe then sure.

Maybe we can put the core small molecule mapping data model in `gufe` and leave the visualization as an `openfe` subclass/extension?

> One problem I can see with the status quo is that if we want to package the non-eq Protocol in the openfe app, there'll be a gross circular dependency

I had the same thought. It's a solvable issue, but yeah, kinda gross. I think `perses` would have to make `openfe` an optional dependency. For `openfe`, we're already treating perses as optional for atom mappers/scorers.

**Comment by IAlibay** [comment]
The viz stuff is something that I know other folks using atom mapping want to use (I know it was a request on alchemiscale and iirc someone mentioned in a perses issue at some point that it would be great to bring over access to the 3D viz stuff).
