### ISSUE TITLE
make settings Readonly once inside Protocol

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#138]
https://stackoverflow.com/questions/67078207/is-it-possible-to-dynamically-change-the-mutability-of-a-pydantic-class

**Comment by IAlibay** [comment]
As per today's discussion, this should go up in priority. If we manage to mess it up, who knows what will happen in users' hands.

**Comment by IAlibay** [comment]
@richardjgowers wants to include this for the 0.7 milestone.

**Comment by richardjgowers** [comment]
@dotsdl @dwhswenson how would we feel about changing the accessor to `Protocol.get_settings()` so it's more explicit that it's not an attribute, and therefore you can't modify it in place?  Or is just toggling the pydantic readonly attribute enough?
