### ISSUE TITLE
RDKit properties are not stored in `SmallMoleculeComponent.to_dict`

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/gufe#145]
Problem illustrated below. However, there's a more fundamental issue that we were originally using RDKit properties to label the version of `gufe` that the molecule came from. So if we do include those in `to_dict`, `SmallMoleculeComponent` would need a custom gufe-key representation that excludes the gufe version properties from the hash.

My proposed solution would be to:

1. Include properties in `to_dict`
2. Remove the additional properties we add for gufe versioning.

Alternate solutions: 

* Custom `_tokenization` method for `SmallMoleculeComponent` that filters the specific properties we add 
* Drop the guarantee that we preserve properties attached to an rdkit molecule -- I'm not sure whether these properties would survive a round-trip to another molecular representation anyway (openff, oechem).

MCVE below (note that this has to be done in separate processes for the error to occur because our flyweight will reuse the same object in the same process).

```python
# dump_smc.py
import gufe
from gufe.tokenization import JSON_HANDLER
from rdkit import Chem
import json

mol = Chem.MolFromSmiles("CC")
Chem.AllChem.Compute2DCoords(mol)
mol.SetProp("foo", "bar")
smc = gufe.SmallMoleculeComponent.from_rdkit(mol)

assert smc.to_rdkit().GetProp("foo") == "bar"

dct = smc.to_dict()
with open("dump.json", mode='w') as f:
    f.write(json.dumps(dct, cls=JSON_HANDLER.encoder))
```

```python
# load_smc.py
import gufe
from gufe.tokenization import JSON_HANDLER
import json

with open("dump.json", mode='r') as f:
    dct = json.load(f)

smc = gufe.SmallMoleculeComponent.from_dict(dct)
assert smc.to_rdkit().GetProp("foo") == "bar"
```

```bash
$ python dump_smc.py
$ python load_smc.py
```

```pytb
Traceback (most recent call last):
  File "/Users/dwhs/Dropbox/omsf/tmp-rdkit-prop-issue/load_smc.py", line 9, in <module>
    assert smc.to_rdkit().GetProp("foo") == "bar"
KeyError: 'foo'
```

**Comment by richardjgowers** [comment]
Yeah this looks a good idea, obviously we'd have to document which Props we're aware of, in case there's any hiding away that we're accidentally missing.

I think not doing this might be as we were initially considering OpenFF Mol as the internal object, which iirc doesn't preserve these fields.

hmm:

https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Wrap/Mol.cpp#L50
