### ISSUE TITLE
Specifying component B to A in ligand mapping

### ISSUE THREAD

**Issue by ijpulidos** [OpenFreeEnergy/gufe#155]
Currently the `LigandAtomMapping` class has a `componentA_to_componentB` parameter that we can use to define the mapping. Some packages or tools might expect a different "directionality" in the mapping, for example [in perses](https://github.com/choderalab/perses/blob/0355528d2332d47d0b1a396785321ada9f6d6fc4/perses/rjmc/topology_proposal.py#L2030) is inverted compared to the convention chosen by `gufe` (hopefully for convenience, but maybe it was just arbitrary on the perses side).

Do we want to have a `componentB_to_componentA` option for the constructor of a `LigandAtomMapping` object? That said, I'd think that we want at least to have it unambiguously defined in the docstring, even for the current parameter.

**Comment by richardjgowers** [comment]
@ijpulidos you mean this? https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/mapping/ligandatommapping.py#L59

**Comment by ijpulidos** [comment]
Oh, that helps, but I meant this https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/mapping/ligandatommapping.py#L25

**Comment by dotsdl** [comment]
Conclusion: a clarifying docstring specifying what the keys, values are in the `componentA_to_componentB` and `componentB_to_componentA` property dicts.
