### ISSUE TITLE
`LigandAtomMapping` validator for mapping

### ISSUE THREAD

**Issue by ijpulidos** [OpenFreeEnergy/gufe#170]
I understand the following could be outside of the scope of the `gufe` objects, since it probably involves a considerable change in the classes/objects, but I thought it was worth of a discussion. 

When playing with the mappings for ligands we can create mappings that include indices that are not found in any of the `SmallMoleculeComponents` involved. Do we want to have a special validator for such cases? Maybe something that checks that the indices in the mapping actually exist in the components. The advantage of having this validated is that it will fail early in the runtime, which is convenient.

I cannot think of cases where we want indices that do not exist in either of the components to be valid in the mapping, but maybe there are some applications or special protocols that would like to use something like that.

**Comment by richardjgowers** [comment]
yes, we can add index checks, something like always positive and always less than n_atoms
