### ISSUE TITLE
Failures as first class results

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#24]
Currently there's not really a way for a `ProtocolUnit` to communicate if/how they failed.  I imagine that as a subclass of `ProtocolUnitResult` we can have a failure class, which could encapsulate any logs/debug info.  This should also properly hold up any dependency chains, so something like `Result.ok() -> bool` returning False for this failure class.

**Comment by dotsdl** [comment]
Closing as this is addressed with `traceback` and `exception` properties on `ProtocolUnitFailure`s.
