### ISSUE TITLE
unpin numpy in conda-forge feedstock?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/gufe#248]
We're currently releasing gufe on CF with `numpy <1.24.0`.

I can't remember exactly why we were doing those anymore, do we want to revisit this pin?

**Comment by richardjgowers** [comment]
We’ve never hit any issues iirc? We not linking etc

**Comment by IAlibay** [comment]
@dwhswenson might remember - there was some reason, maybe in openfe

**Comment by dwhswenson** [comment]
IIRC, this is numba/numpy incompatibility introduced almost a year ago. Guess I didn't make a tracking issue on OpenFE; here's the OPS issue for it: https://github.com/openpathsampling/openpathsampling/issues/1127

Looks like numba > 0.57 should fix: https://github.com/numba/numba/releases/tag/0.57.0

**Comment by mikemhenry** [comment]
Yes so we should drop the numpy pin and add a numba > 0.57 pin (but really this should be take care of by our deps that use numba, not us if we can help it)

**Comment by dwhswenson** [comment]
Looks like this has been previously dealt with. I don't see `numpy` pins in either:

* [our gufe environment.yml](https://github.com/OpenFreeEnergy/gufe/blob/ae96d30952a4e000fcb690443a6dbd79ec31756a/environment.yml#L8)
* [our gufe feedstock](https://github.com/conda-forge/gufe-feedstock/blob/main/recipe/meta.yaml#L26)

Closing issue as completed.
