### ISSUE TITLE
`pip install git+https://github.com/openfe/gufe.git` hangs on Github username prompt

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/gufe#26]
Running the following, I get:

```bash
$ pip install git+https://github.com/openfe/gufe.git
Collecting git+https://github.com/openfe/gufe.git
  Cloning https://github.com/openfe/gufe.git to /tmp/pip-req-build-6686emdb
  Running command git clone --filter=blob:none -q https://github.com/openfe/gufe.git /tmp/pip-req-build-6686emdb
Username for 'https://github.com':
```

The same occurs when I instead try to install `openfe/openfe.git`. This *does not* happen with other repos, such as `datreant/datreant.git` or `openforcefield/openff-toolkit.git`.

Note that doing a:

```
git clone https://github.com/OpenFreeEnergy/gufe.git
```
works as expected, but doing a:
```
git clone --filter=blob:none --quiet https://github.com/openfe/gufe.git
```
results in the username prompt.

Is there an org-level setting in OpenFreeEnergy that's causing this behavior?

**Comment by dwhswenson** [comment]
`datreant/datreant` and `openforcefield/openff-toolkit` both have a `master` branch. `openfe/gufe` and `openfe/openfe` do not. Any chance this is the source of problem?

**Comment by dotsdl** [comment]
Just tried doing:

```
pip install git+https://github.com/openfe/gufe.git@main
```
and I get the username prompt still. Doing
```
pip install git+https://github.com/datreant/datreant.git@master
```
doesn't yield a prompt at all. Still scratching my head on what could be happening here.

**Comment by richardjgowers** [comment]
@dotsdl s/openfe/OpenFreeEnergy/

**Comment by dotsdl** [comment]
:facepalm: thanks @richardjgowers!
