### ISSUE TITLE
Improve readability of the settings when printed out

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/gufe#263]
From a call today with @hannahbaumann - it feels like the way in which we look at settings is too messy to be accessible to users. Is there a way we could improve the `__repr__` or something like that to make it prettier?

**Comment by richardjgowers** [comment]
I think `__repr__` is meant to be a single line string, so probably not with that.  `__str__` would make `print(str(settings))` better.  Are you also thinking about the file representation too?

**Comment by IAlibay** [comment]
I think just changing the `print` behaviour would be fine - it's mostly a case of having a nice way to look at the output.

maybe just make `__str__` return `settings.dict()`? (at least pprint on that looks good)

**Comment by richardjgowers** [comment]
yeah `__str__` being `pprint(settings.dict())` seems very useful.  If we're being fancy we could also make that the jupyter hook whatever that's called
