### ISSUE TITLE
Serialization mixin has unimplemented methods

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#29]
The `Serialization` mixin we're using from openff-toolkit requires `to_dict` and `from_dict` to implement a lot of other serialisation (which is great) but also requires `to_toml` and `from_xml`.  My IDE is constantly complaining that the `abc` isn't properly filled.  Maybe we can strip the xml and toml out from this mixin?

**Comment by dwhswenson** [comment]
Have we dropped the `Serialization` mixin across the board (in favor of `GufeTokenizable`)? If so, this issue should be closable.

I'm in favor of not including XML and TOML serialization, as long as there's a `to_dict` available -- anyone who really wants those formats should be able to get there from the dict representation.

**Comment by richardjgowers** [comment]
Yeah I think we’re going solo for serialisation as we mean something
slightly different (ours is archival)

**Comment by richardjgowers** [comment]
We're going for gufe tokenizables across the board
