### ISSUE TITLE
ChemicalSystem difference method

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/gufe#347]
## User story

It would be good to have a method built into ChemicalSystem that checks how it differs from another ChemicalSystem and have it return a dict of list of components that are different.

**Comment by dotsdl** [comment]
May require some feedback from the protocol devs group. @ijpulidos do you have thoughts on the output data structure you'd like to see from this?

**Comment by IAlibay** [comment]
Note: not saying this is the right data structure, just how we're using this downstream.

In `openfe`, our chemical system difference method returns a `dict[str, list[Component]]` which is keyed as `stateA` and `stateB` and contains all the "unique" components for each state.

Maybe doing a tuple of bools would be better?
