### ISSUE TITLE
Get connected subgraphs in an  `AlchemicalNetwork` 

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/gufe#383]
[From Irfan](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/156#discussion_r1827612898) 
> This is a perfectly fine strategy. In the future we should see if we can extend the `.graph` method of AlchemicalNetwork objects to offer this kind of convenience. I.e. "get me all the connected subgraphs".

**Comment by dotsdl** [comment]
This subgraphs method on an `AlchemicalNetwork` could return the subgraphs as `AlchemicalNetwork`s themselves.
