### ISSUE TITLE
`ProtocolDAG.protocol_units` no longer returns a name sorted list of units.

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/gufe#387]
Looks like a "bug" introduced in #315 

## Previous behaviour

When calling `ProtocolDAG.protocol_units` multiple times, your first element would always be your last repeat (if your name was written as repeat "<repeat_num> generation <generation_num>").

## Current behavior

The order of repeats is not guaranteed as they are sorted by their protocol keys.

**Comment by IAlibay** [comment]
I quote this as a "bug" because `unit.name` is just an arbitrary string, which may or may not sort in the way you want it to.

**Comment by IAlibay** [comment]
I'm tempted to call this "not a bug", because we were erroneously sorting in a bad manner - @dotsdl do you agree?

**Comment by dotsdl** [comment]
@IAlibay from our discussion, we concluded that the new behavior is desirable over the old behavior, and that the existing behavior of name-based sorting was never really intended and should not be relied upon.
