### ISSUE TITLE
Squash PRs into main

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/gufe#417]
I think we should squash PRs into main since most people don't rebase PRs, so often many commits are in a broken state, so merging them in reduces how well git bisect will work. If we squash every PR into main, then every commit on main should build/pass tests, which makes it easier to track things down with git bisect. Personally, I squash in the PRs, but I feel like unless we set that up in the repos settings, people will forget.

**Comment by dotsdl** [comment]
I'm fine with setting squash merges as the default.

Any objections @OpenFreeEnergy/core-devs?

**Comment by ianmkenney** [comment]
@mikemhenry 100% agree

**Comment by atravitz** [comment]
@mikemhenry @ianmkenney same, I'm very much in favor of squash merging.

**Comment by IAlibay** [comment]
I generally prefer squash merge, it keeps history a lot cleaner. Indeed I believe I voted for it at the start of OpenFE but was outvoted.

That being said, the votes against did lay out a convincing argument that it was an issue when you split work across multiple PRs with the same history. It's not a development pattern I do, so it doesn't affect me, but I can see how it can be a problem in those cases.

**Comment by mikemhenry** [comment]
I've made this change
