### ISSUE TITLE
Consider alternative names?

### ISSUE THREAD

**Issue by jchodera** [OpenFreeEnergy/gufe#6]
I'm excited by the rapid progress on this repo!

I was wondering if I could persuade you to consider a more informative name, perhaps in a unified Open Free Energy namespace. The Open Force Field folks eventually came to the conclusion that it was important to have a unified namespace where various component packages could live in a relevant name subspace:
* `conda install openff-toolkit` would install the `openff.toolkit` package
* `conda install openff-evaluator` would install the `openff.evaluator` package
* `conda install openff-forcefields` would install the force fields
and so on. This made it very easy to identify what was produced by Open Force Field (the `openff` prefix) and the various packages installed cleanly into namespace subspaces.

As an alternative to the goofy name "gufe", perhaps OpenFE might consider adopting a common namespace (`openfe` is an obvious choice) and clear, succinct naming conventions? For example
* `conda install openfe-core` could install the `openfe.core` common component object models; alternatives could be `openfe.common` or `openfe.components`
* `conda install openfe-toolkit` could install `openfe.toolkit` with common toolkit components (currently in [`openfe/openfe`](https://github.com/OpenFreeEnergy/openfe))
* `conda install openfe-lomap` could install `openfe.networkmapper.lomap` if you want to break up mappers by flavor, or you could unify everything under `openfe.networkmapper` to install one or more network mappers.
* `conda install openfe-perses` could install `openfe.engine.perses` to manage perses calculations, while other simulation engine wrappers could be installed similarly (`openfe-gromacs` -> `openfe.engine.gromacs`)
* `conda install openfe-atommapper` could install `openfe.atommapper.leadoptmap` as an atom mapper
and so on.

**Comment by dotsdl** [comment]
In today's call we settled the discussion on naming. OpenFE is deliberately avoiding a namespace-package-based approach, and `gufe` is in alignment with this. The `openfe` package is intended as the sole user entrypoint to the OpenFE ecosystem, with packages like `gufe` and others in the future used internally at will alongside packages produced by other communities. The intention is to avoid an exclusionary distinction between OpenFE-affiliated and -unaffiliated packages to help attract contributors.
