### ISSUE TITLE
Gufe, Single file serialisation dumps

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#71]

**Comment by dwhswenson** [comment]
Currently, this is just

```python
import json
with open(filename, mode='w') as f:
    json.dump(transformation.to_dict(), f)
```

Do we need to wrap that into a 1-line `transformation.dump` (with a corresponding `transformation.load`), or is the current version enough?

If we wrap it, I think this is `Transformation`-specific; not for all gufe objects. For example, networks might dump to a non-JSON format to avoid information duplication.

**Comment by dwhswenson** [comment]
With custom JSON support, this is now:

```python
      import json
      from gufe.tokenization import JSON_HANDLER
      with open(filename, 'w') as f:
          json.dump(transformation.to_dict(), f, cls=JSON_HANDLER.encoder)
```

Can we consider this task completed, or do we need anything else for it?

**Comment by richardjgowers** [comment]
Yeah ok, I think `Transformation.dump()` is enough.  Tbh I can't remember if @dotsdl is even using `Transformation`, I think even that is just an openfe hack.

**Comment by dwhswenson** [comment]
👍 Will have a PR started by end of day. (I think he's using `Transformation`, though)

**Comment by dotsdl** [comment]
I'm definitely using `Transformation`; I'm also using `AlchemicalNetwork`, which is built out of `Transformation`s and `ChemicalSystem`s.
