### ISSUE TITLE
Remove openeye dependency?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/gufe#8]
So I know we have it lying around because of the old Molecule stuff, but since we can do gufe -> OFF -> OpenEye, can just get rid of this explicit dependency?

**Comment by IAlibay** [comment]
To better explain what I'm requesting here, we have explicit "to_openeye" methods in various places, it seems somewhat unecessary?

**Comment by richardjgowers** [comment]
So strictly speaking oechem is an optional dependency.  I guess the `to_openeye` methods are redundant if you know that us->off->openeye exists though.
