### ISSUE TITLE
Failing old openff-toolkit

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/gufe#92]
Settings (#37) was merged while it was failing on tests for the old version of openff-toolkit (0.10).

Are we removing that from the test matrix, or does that need to be fixed? Revert the merge for now so that the red doesn't make it harder to review PRs that aren't failing?

How much longer do we need to support the old toolkit?

**Comment by richardjgowers** [comment]
I thought I’d removed it after the last release.

**Comment by dwhswenson** [comment]
Resolved by merging https://github.com/OpenFreeEnergy/gufe/pull/78
