### ISSUE TITLE
Add a `DummyProtocol` or similar that functions as a placeholder for users, docs

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/gufe#96]
We want a `DummyProtocol` or similar that allows users to prototype alchemical networks without having to make any actual `Protocol` choices upfront. This would be especially useful right now as actual protocol implementations are being actively developed.

**Comment by dwhswenson** [comment]
Is this not in the test suite already? I've been using that for development purposes where I needed a protocol to use (e.g., for our `quickrun` CLI input setup: https://github.com/OpenFreeEnergy/openfe/blob/main/openfecli/tests/dev/write_transformation_json.py

**Comment by dotsdl** [comment]
Indeed, we could use that one. I was thinking of this as an "official" placeholder that might be used in docs, examples, etc., in which a user is more focused on building an alchemical network than their choice of protocol. It should probably have a different name than the `DummyProtocol` given in the test suite to avoid confusion.

I can work with the existing `DummyProtocol` in the test suite for now; happy to close this issue if the above isn't of interest.
